### ISSUE TITLE
PAUSE BUTTON

### ISSUE THREAD

**Issue by 201BusProject** [201BusProject/201busproject#12]
1. how do i know something like a pause button exists?
2. even if the pause button exists it doesn't allow me to choose a new destination.

**Comment by pranman11** [comment]
1. @Vrroom said we should let the user figure out that the journey pauses on clicking the bus. I think allowing the user to discover this feature instead of making it obvious, would be cool. What do you think?
2. I was wondering if there's any need for a reset button like we had earlier?

**Comment by Vrroom** [comment]
2. You mean a cancel button? yeah that'll be useful. Both for the user and debugging 😃
