### ISSUE TITLE
IMAGE /ILLUSTRATIONS

### ISSUE THREAD

**Issue by 201BusProject** [201BusProject/201busproject#13]
1. Sometimes the image/illustrations take time to load. 
2. Arrow is still not that visible?

**Comment by Vrroom** [comment]
Those images are the only thing that we are fetching from google drive. We'll add them to the static folder as well.

**Comment by 201BusProject** [comment]
ok

**Comment by Vrroom** [comment]
Can someone share the link of the folder containing these illustrations?

**Comment by 201BusProject** [comment]
Check whatsapp

**Comment by Vrroom** [comment]
Can you confirm that loading is smoother than before now? If still unsatisfactory, I'll vectorize the images and serve the SVGs

**Comment by Vrroom** [comment]
Also, which arrows are you talking about?

**Comment by 201BusProject** [comment]
Still yet to check images.
Arrows next to the images to change the images.

**Comment by pranman11** [comment]
I will try to change the color of the arrows or make it larger.
