### ISSUE TITLE
WHY DO SOME ROUTES MOVE AUTOMATICALLY ?HOW DO I KNOW SOMETHING IS A CONTINOUS ROUTE?

### ISSUE THREAD

**Issue by 201BusProject** [201BusProject/201busproject#16]
1. I understand this happening when lets say I choose to take a bus from srinagar to jeevan bhima nagar. It will stop at BNS and then take another bus to JBN. As a user I don't understand why it stopped at BNS and changed buses. to me it seems like the website made a glitch and is making me take anothe rbus to another destination. Only aferwards you realise that it is taking you to the right destination but there is a possibility that a user could forget his destination. This happened to me. once the bus stopped at BNS I forget I had chosen JBN and there was another leg of the journey left. 

How do we address this? Do we have a pop saying Srinagar to JBN that stays till the end regardless of the switch in buses ?

2. Sometimes a new journey would start and complete and immediately without me getting to getting to choose a new destination or the popup showing up saying pick a new destination, it would go straight into another journey. Why is this the case. Shouldn't all journeys once ended and a new one begins should give an option saying pick destination right?

**Comment by pranman11** [comment]
1. We can have either a) the entire journey from source to destination shown using a translucent color as mentioned by @Vrroom or b) Have the destination shown using a pop up over the destination stop.

2. I am not quite getting this or might not have come across this case.
