### ISSUE TITLE
SUBMISSION OF THE GRANT- FORMAT 

### ISSUE THREAD

**Issue by 201BusProject** [201BusProject/201busproject#20]
I had told them that HTML is not possible

This is the response I got. 
Not too worrying I think? I think you two would be able to tell me better whether it is or not. I'll wait for you two to see this and hear what you have to say and then reply to them. 

_**'For the website: We request a static version of the website because sometimes after a few years if the site is dissolved or dead, we will still have something that would give an impression (however incomplete it is) of what it looked like and what it had. If possible, save the main pages as PDFs and give us those in a folder. As long as the website is alive, we will only share the link with your project page on the online archive of IFA. But just in case sometime in future it goes off-net, we want to have some documentation of what happened there. We may upload these PDFs (if you agree, of course) if the website is not active any more in future. Does this make sense? 
You can also copy the full folder structure of the site along with all files (that you place in 'htdocs' folder if you are using a server software like Xampp) and softwares that are required to be installed in the server on a pen drive which we will keep safe with the other materials that you submit. These will not be uploaded or used in any way, but remain with the archive as documentation and backup.'**_

**Comment by Vrroom** [comment]
Sounds good. Or they can take the whole code + data repository. We'll try to provide as thorough documentation as possible so that they can run the website on their own

**Comment by 201BusProject** [comment]
okay. Then I will accordingly respond. I don't think you need to make that detailed but if that's doable and takes less time then fine.
