### ISSUE TITLE
PROBLEMS A USER COULD FACE 

### ISSUE THREAD

**Issue by 201BusProject** [201BusProject/201busproject#5]
1. the bus stops need to be highlighted so that the user knows where he or she is at. 
2. They need to be told to pick a destination. 
3. I did not know there was a pause feature until Sumit told me yesterday. Is there a way our features can be clearer to the users?
4. why does the next journey start automically in some and not the others?
5. should different colours be used to show which 201 they are taking? we need to create some tag on teh bus or something so that the user knows which bus he or she is on
6. when I clicked girinagar to srinagar, it took me to banashankari first and then it started the next leg of the journey to Srinagar. I was confused at first but then i realised it has to go via banashankari. Is there a way to show they entire route so that a user knows that it is not a mistake?

**Comment by Vrroom** [comment]
4. Can you give specific examples? 
5. Yeah, I agree, tag is better than color. Should we write the bus no on the road or along the road. Like on google maps it writes akbar road on the road, maybe next to the route, we can have text saying 201C or whatever? 
6. There is a way to show the entire route. Some translucent color would be best.

**Comment by pranman11** [comment]
2. I have added a toast that shows up saying "Pick a destination" when user clicks any bus stop first. It disappears once the destination stop is selected.

**Comment by Vrroom** [comment]
@pranman11 Looks good!

**Comment by 201BusProject** [comment]
5. I have added the label/text-field that comes up along the route when the bus journey is on. This is visible for longer routes like from Hampinagar/Jeevan Bhima Nagar/Domlur but is not visible for shorter routes yet, unless you zoom in. On zooming in you can see the labels.

I was also wondering if we should bring back the zooming in/fly to feature which was there earlier. to focus on the current bus journey? We had chosen to remove that earlier because I think loading zoomed map was making things slow on some machines.

**Comment by Vrroom** [comment]
Actually for the 201Q bus on a longer path, this is also true. Need to zoom in to see the label.
