### ISSUE TITLE
VISUALS

### ISSUE THREAD

**Issue by 201BusProject** [201BusProject/201busproject#6]
1. Bus stop- need an icon for that / how do we incorporate them?
2. Bus - needs to show which 201 it is taking
3. Bus route- what colour? and it should end underneath the bus icon
4. Need to add the anecdotes again
5. Have a table/ legend on the map maybe to tell the user about the bus and the bus stops it goes through?
6. Changes to About page - Content + Visuals 
7. Font- Helvetica 
8. Footer

**Comment by Vrroom** [comment]
4. I added anecdotes in #4.
5. I think we should have a table and a slightly translucent tooltip on the bus stop and path to highlight which bus/bus stop

**Comment by pranman11** [comment]
Closing this as point 5 is covered in another issue.
