### ISSUE TITLE
URL 

### ISSUE THREAD

**Issue by 201BusProject** [201BusProject/201busproject#7]

**Comment by Vrroom** [comment]
Make an account on Heroku and give me the account details. I'll move the app there. Then our URL will be something like:

201busproject.herokuapp.com 

We can perhaps get rid of __herokuapp__ too. IDK how of the top of my head.

**Comment by 201BusProject** [comment]
1. I will need to write about why we chose Herokuapp instead of Github. What does it offer that GIthub doesn't?
2. Pranav mentioned that H.app doesn't allow you to start a website with a number. Hence bus201 right? I think that's fine. Can't think of any other name just yet. perhaps The201busproject? Need to think about this. 
3. As of now all the pages- about page, sound page and everything else have the same URL. Is that an issue you are all also facing?

**Comment by 201BusProject** [comment]
1. We chose Heroku because we were facing issues with the URL on GitHub -- 201busproject was appearing twice or thrice? That was the reason right?

3. That is not an issue actually. We have not created different pages in the code. Its a single page where different components (about, sound, map) are set (does that make sense?). 

We can have different pages and hence different URLs. Like we had earlier -- that would also make the back (and reload) button work, as mentioned in #11 .

**Comment by Vrroom** [comment]
Ok I'm closing this issue for now. We can always continue the remaining discussion in #11
